version: "3.9"

services:
  langgraph_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: langgraph_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      uvicorn app.api.main:app
      --host 0.0.0.0
      --port 8000
      --workers 4